### ISSUE TITLE
Settings parameters DETECTOR_STATION & DETECTOR_STATION_LIVETIME_CONFIG not initialized

### ISSUE THREAD

**Issue by mingyuanlu** [ara-software/AraSim#14]
`Settings` parameters `DETECTOR_STATION` and `DETECTOR_STATION_LIVETIME_CONFIG` not given any initial value. This may cause errors on runtime due to random numbers being assigned to them. 

Error message example:
`DETECTOR_STATION_LIVETIME_CONFIG is set to 1970565737 
DETECTOR_STATION_LIVETIME_CONFIG is set to 1970565737 but there are only five expected configurations
There are 1 errors from settings. Check error messages.` 

The fix should be simply to initialize these parameters in `Settings.cc`

**Comment by toej93** [comment]
How did you get that error?

**Comment by mingyuanlu** [comment]
By simply running AraSim without specifying those parameters in the setup file. Since the parameters are not initialized, during compile time the compiler assigns memory for the variable but the "content" of that memory location is arbitrary. So at runtime the application tries to read that content and in my run it turns out to be a very large number which fails the check. To eliminate this arbitrariness the parameters should be initialized.

**Comment by toej93** [comment]
Got it. Will you fix that?

**Comment by mingyuanlu** [comment]
It's fixed in PR #15
