### ISSUE TITLE
Antenna polarization bug

### ISSUE THREAD

**Issue by toej93** [ara-software/AraSim#25]
Ben  ( @bhokansonfasig ) reported a bug some time ago regarding the way AraSim applies the gain factors to the incoming signal. In summary, the polarization is accounted for twice. You can see a more detailed explanation on his slides: http://ara.physics.wisc.edu/cgi-bin/DocDB/ShowDocument?docid=1947

**Comment by bhokansonfasig** [comment]
The factor of `-sin(theta)` isn't fully explained in the slides, so I'll add that here:

On slide 5 I claim that the projection of `p-hat` onto `z-hat` done in AraSim is unnecessary, and the proper projection which should be applied is `p-hat` onto `theta-hat`. The dot product of `p-hat` and `z-hat` is `sin(theta)`, whereas the dot product of `p-hat` and `theta-hat` is `-1`, which means the extra factor that AraSim is applying works out to `-sin(theta)`
