### ISSUE TITLE
E^-2 mode(EXPONENT=2) generates the event that out of the sigma range and makes simulation froze

### ISSUE THREAD

**Issue by MyoungchulK** [ara-software/AraSim#28]
I'm trying to run the AraSim with 'E^-2' mode(`EXPONENT=2`). But somehow simulation is always stopped with this message (`Need a parameterization for this energy region.(new)`). It happens when `pnu` is outside of the `SIGMAPARAM` in `Primaries::GetSigma`. 
The defined SIGMAPARAM ranges are 1e+13 to 1e+21. But sometimes we are observing `pnu` is over the 1e+21. It caused stopping simulations and not properly closing it. Simulation needs to change to not generate `pnu` outside of sigma range or discard when it happens.
![Untitled](https://user-images.githubusercontent.com/53809378/98247969-abfea280-1fb7-11eb-9e5f-92fab020e746.png)

**Comment by clark2668** [comment]
This was handled in PR #29.
