### ISSUE TITLE
Simulation is crashing by TraceFinder::refineRoot

### ISSUE THREAD

**Issue by MyoungchulK** [ara-software/AraSim#37]
Sometimes simulation is crashing by this message. 
Trying to figure out what is causing it.
![Untitled](https://user-images.githubusercontent.com/53809378/101272949-572b9300-37d4-11eb-8d9a-7b34f37b6422.png)

**Comment by clark2668** [comment]
Hey Myoungchul--I've never actually seen this error before! That looks like an error in the trace finder. Can you identify a specific neutrino interaction that's causing the error? That will likely help us figure out what the problem is.

**Comment by MyoungchulK** [comment]
It happened when I use E^-1. I will back soon when I successfully recreate this crash with some debug messages.

**Comment by clark2668** [comment]
Okay, thanks! Once we have a vertex that causes the issue, I'm confident we'll be able to sort it.

**Comment by MyoungchulK** [comment]
the error message is in [TraceFinder::refineRoot](https://github.com/ara-software/AraSim/blob/383f6290ec1061111feebd0510196653f84c66a2/RayTrace.cc#L1061) and [TraceFinder::evenmore_refineRoot](https://github.com/ara-software/AraSim/blob/383f6290ec1061111feebd0510196653f84c66a2/RayTrace.cc#L971) in `RayTrace.cc`.
In the code, when` if(i==maxTests)` is acquired, simulation is [throw](https://github.com/ara-software/AraSim/blob/383f6290ec1061111feebd0510196653f84c66a2/RayTrace.cc#L1035) the error message.

Currently, trying to figure out exactly how the refineRoot is working and what is the purpose. And put more debug messages to check what will be happening. Simulation is running until account the bug. In the current understanding, it is not related to flavor, NuBar, or current. Gonna check the vertex position and ray path, too.

[TraceFinder::refineRoot](https://github.com/ara-software/AraSim/blob/383f6290ec1061111feebd0510196653f84c66a2/RayTrace.cc#L1061)

![Untitled](https://user-images.githubusercontent.com/53809378/101483998-4cbbf580-399c-11eb-8de2-9e79f5d5afcc.png)

[TraceFinder::evenmore_refineRoot](https://github.com/ara-software/AraSim/blob/383f6290ec1061111feebd0510196653f84c66a2/RayTrace.cc#L971)

![Untitled1](https://user-images.githubusercontent.com/53809378/101484011-50e81300-399c-11eb-917d-9e26b1359132.png)

**Comment by clark2668** [comment]
Usually such statements are put into numerical solvers to prevent them from running forever in the cases where they cannot find solutions within a specified tolerance. You could imagine increasing `maxTests` if it's almost there. But sounds good, thanks for debugging. I'd expect this to be a function of vertex location only by the way!

**Comment by MyoungchulK** [comment]
Based on the bugs I found, They happen when the vertex is placed around 12km far away from the antenna.

Example:
targetZ:-181 -> antenna z position
targetD:11615.5 -> xy plane distance between antenna and vertex
emit_depth:-2553.57 -> vertex z position
launch angle: 1.35992 -> 77.91767648 degree
missing_z: -0.208801 m-> little over the z tolerance(0.2 m)

Before the simulation calculates a full ray solution(`doTrace<fullRayPosition>`), the raytracing(`RayTrace.cc`) tries to minimize computational time by setting the searching range for full ray solution by `estimateRayAngle`. `estimateRayAngle` will show which launch angle (the searching range) to focus in, but if the estimated result is [over the z tolerance](https://github.com/ara-software/AraSim/blob/383f6290ec1061111feebd0510196653f84c66a2/RayTrace.cc#L1384), `refineRoot` and `evenmore_refineRoot` will narrow down the searching range more tightly.

In the `refineRoot` and `evenmore_refineRoot`, `maxTests` defines how many tests to conduct by the [for loop](https://github.com/ara-software/AraSim/blob/383f6290ec1061111feebd0510196653f84c66a2/RayTrace.cc#L995). But the for loop index `i` is defined as  `unsigned int i`, it can go to infinite until they find the solution. Regarding the typical bug case,when the distance between antenna and vertex is far (~12km),  -0.2088 m(missing_z) is already the maximum estimation they can get, no matter how many for loop it runs, `doTrace<minimalRayPosition>` inside the for loop cannot get a smaller number than -0.2088 m. It is more like showing the missing_z as a huge number like -9.56627e+19, which is failed ray tracing, from the beginning of the for loop. 

When the index `i` reaches `maxTests`([link](https://github.com/ara-software/AraSim/blob/383f6290ec1061111feebd0510196653f84c66a2/RayTrace.cc#L1029)), the simulation executes `throw` command and results in a crash (Aborted). We don't want to lose all the simulation results by this event and we also don't want to say 12km is a simulation limit (in the real case, it will be very rare, but good to have this possibility working for the simulation?), right?

My suggestion is, if `refineRoot` and `evenmore_refineRoot` fail to narrow down the searching range, we keep the original estimated range from `estimateRayAngle` and pass into `doTrace<fullRayPosition>`. Since 1) this is the maximum estimation we can get by `estimateRayAngle` 2) original missing_z from `estimateRayAngle` in this bug case is tight enough(0.2~3m) 3) `doTrace<fullRayPosition>` also has a fail safe after function([if ( std::abs(results.front().miss) > requiredAccuracy ) {](https://github.com/ara-software/AraSim/blob/383f6290ec1061111feebd0510196653f84c66a2/RayTrace.cc#L1403)), I believe it is  a better way to bypass this bug than throwing the whole simulation.

The expected bypass code will be more like below:
In the [refineRoot](https://github.com/ara-software/AraSim/blob/383f6290ec1061111feebd0510196653f84c66a2/RayTrace.cc#L1126) and [evenmore_refineRoot](https://github.com/ara-software/AraSim/blob/383f6290ec1061111feebd0510196653f84c66a2/RayTrace.cc#L1035) functions:

![Untitled](https://user-images.githubusercontent.com/53809378/102008877-eb6a9c80-3d76-11eb-92eb-0d24fc9f8301.png)

In the [findPaths](https://github.com/ara-software/AraSim/blob/383f6290ec1061111feebd0510196653f84c66a2/RayTrace.cc#L1388) function:

![Untitled1](https://user-images.githubusercontent.com/53809378/102008915-3e445400-3d77-11eb-83c7-a5206da7c73d.png)


But I have to say I need to compare computational time differences and results of raytracing.
It will be updated soon.

Let me know what you guys think so I can do the pull request :)

**Comment by MyoungchulK** [comment]
Below, I plotted the values that I can get from `evenmore_refineRoot`
1) [std::cout << "Fast Solution not close enough (" << results.front().miss << "), pathLen: "<<results.front().pathLen<<"; refining" << std::endl;](https://github.com/ara-software/AraSim/blob/383f6290ec1061111feebd0510196653f84c66a2/RayTrace.cc#L1386)
2) [std::cout << "\ttesting theta=" << a << std::endl;](https://github.com/ara-software/AraSim/blob/383f6290ec1061111feebd0510196653f84c66a2/RayTrace.cc#L1002)
3) [std::cout << "\t second (miss=" << aTrace.miss << ") at angle: "<<a<< std::endl;](https://github.com/ara-software/AraSim/blob/383f6290ec1061111feebd0510196653f84c66a2/RayTrace.cc#L1011)
4) `seed.miss` (the initial missing z to the antenna z position from `estimateRayAngle`), 
5) angle_min and angle_max (searching range for `evenmore_refineRoot`)

bug event configuration is like this
targetZ:-181 -> antenna z position
targetD:11717 -> xy plane distance between antenna and vertex
emit_depth:-2572.93 -> vertex z position
initial missing_z: -0.350696,3 m-> little over the z tolerance(0.2 m)

![다운로드](https://user-images.githubusercontent.com/53809378/102040965-8adc6d80-3e11-11eb-9638-d5cd2db2ab0f.png)

It looks like [aTrace](https://github.com/ara-software/AraSim/blob/383f6290ec1061111feebd0510196653f84c66a2/RayTrace.cc#L1003) in `evenmore_refineRoot` tries to get close to z_tolerance (goal 0.2 m), but it bounced off before reaching the initial missing_z(`seed.miss`) and goes crazy (-9.56767e+19 m !!). 
fiy; Since the for loop is using `unsigned int i` as an index, they can test over the `angle_max`(infinitely)

In the code, the ways to **complete** `evenmore_refineRoot` are whether 
1) missing_z(`aTrace.miss`) is smaller than z_tolerance (0.2 m)
or
2) missing_z(`aTrace.miss`) * initial missing_z(`seed.miss`) is below than 0

In this bug case, none of them are stopping this bug event.

Based on this plot, a better **better** way to avoid this `throw` command is, after the for loop is finished (`if(i==maxTests)`), if the closest `aTrace.miss` is still bigger than `seed.miss`, just use the `seed.miss` as a result(return) of the `evenmore_refineRoot` function. This is the same suggestion I did in the previous comment (if `refineRoot` and `evenmore_refineRoot` fail to narrow down the searching range, we keep the original estimated range from `estimateRayAngle` and pass into `doTrace<fullRayPosition>`.).
fiy; returning the closest `aTrace.miss` option would be not a good option. Since it is bigger than `seed.miss`, it will only increase computational time.

It looks like the `evenmore_refineRoot` function is also keeping the closest `aTrace.miss` as [min_miss](https://github.com/ara-software/AraSim/blob/383f6290ec1061111feebd0510196653f84c66a2/RayTrace.cc#L1006). 
But it is not used anywhere... I believe this was used somewhere in the past but now it is ignored by some updates.

I believe I can use this `min_miss` for fixing this bug.

The expected modified code will be more like below:
In the `refineRoot` and `evenmore_refineRoot` functions:

![Untitled3](https://user-images.githubusercontent.com/53809378/102046260-51f6c580-3e1e-11eb-9cfa-03e3da0068d9.png)

![Untitled4](https://user-images.githubusercontent.com/53809378/102046265-54591f80-3e1e-11eb-97c0-cdf13a2358d1.png)

In this case, we don't have to put additional modifications in the `findPaths` function.

Or we can just consider `if(i==maxTests)` is sign of the `refineRoot` and `evenmore_refineRoot` fails. and just keeping the result from the  `estimateRayAngle`.

![Untitled5](https://user-images.githubusercontent.com/53809378/102047579-d77b7500-3e20-11eb-8ef0-22caec4dfa38.png)

Or as Brian suggested, we can increase [maxTests](https://github.com/ara-software/AraSim/blob/383f6290ec1061111feebd0510196653f84c66a2/RayTrace.cc#L988) and check whether more fine `testing theta` bin can pass z_toleance (goal 0.2 m) or not.
changing [testDisp](https://github.com/ara-software/AraSim/blob/383f6290ec1061111feebd0510196653f84c66a2/RayTrace.cc#L985) will increase [maxTests](https://github.com/ara-software/AraSim/blob/383f6290ec1061111feebd0510196653f84c66a2/RayTrace.cc#L988) value.
I will update this result(w/ simulation run time differences) soon:)

Let me know what you guys think so I can do the pull request :)

**Comment by clark2668** [comment]
Based on a plot you sent me, it doesn't seem like increasing maxTests gets us closer. Which is closer to right--`min_miss` or `seed.miss`?

**Comment by MyoungchulK** [comment]
I ran some simulations with `RANDOM_MODE=0`(debug mode).

When I ran the simulations
I changed [testDisp](https://github.com/ara-software/AraSim/blob/383f6290ec1061111feebd0510196653f84c66a2/RayTrace.cc#L985) to 0.00001, 0.000001, 0.0000001.
In this bug event, `maxTests` will be 400, 4000, 40000
I also changed [testDisp*=2.0;](https://github.com/ara-software/AraSim/blob/383f6290ec1061111feebd0510196653f84c66a2/RayTrace.cc#L997) to 1.5.

So, the tested casees are,
1) 400, 2.0
2) 400, 1.5
3) 4000, 2.0
4) 4000, 1.5
5) 40000, 2.0

Below the plot is the result of the different settings.
![다운로드 (1)](https://user-images.githubusercontent.com/53809378/102089044-0d3f4e80-3e5f-11eb-889a-2b33815b93e9.png)

Based on what I got, no matter how we changed the setting. I think it is not going to satisfy the z_tolerance limit. 
But one case(4000, 1.5) is going down to seed_miss.
I think this is more likely RK diff.equation issue

But based on '4000, 1.5' case. Maybe good to use second v2 solution. In that case, at least we can get a more tight searching range than use initial missing z estimation.

![Untitled4](https://user-images.githubusercontent.com/53809378/102092925-ecc5c300-3e63-11eb-993c-9d7220c6b29b.png)

**Comment by MyoungchulK** [comment]
> it doesn't seem like increasing maxTests gets us closer. Which is closer to right--`min_miss` or `seed.miss`?

In '4000, 1.5' case, `min_miss` is maybe close to right one.
But in other cases, probably good to use `seed.miss`

It means some of the case, `min_miss` can go closer to z_tolerance than  `seed.miss`. But not good enough for `refineRoot` purpose(smaller than z_tolerance).
