### ISSUE TITLE
compilation with -fPIC flag

### ISSUE THREAD

**Issue by toej93** [ara-software/AraSim#5]
I tried to compile AraSim and it threw the following error:

`/usr/bin/ld: Efficiencies.o: relocation R_X86_64_32 against .rodata can not be used when making a shared object; recompile with -fPIC`

I added `-fPIC` to the MakeFile and it compiled without any issues. Is there a reason why that flag was removed?

**Comment by cozzyd** [comment]
I don't think -fPIC was ever removed (at least not by me). In fact, it should be properly be generated by the Makefile.arch file. It's possible you're using an environment that the Makefile.arch file (which is copied from an ancient ROOT distribution... hence the hpux and sunos references)
