### ISSUE TITLE
DETECTOR_STATION=0 (TestBed) causes memory corruption

### ISSUE THREAD

**Issue by mingyuanlu** [ara-software/AraSim#7]
Changing DETECTOR_STATION from 2 to 0 (TB) in the default `setup.txt` file causes memory corruption at run time, without any warning or error message regarding incompatible `Settings` parameters.

Error messages at run time that may or may not be related
`Error, station number not match !`
`No string/antenna matches the channel number`
`AraStationInfo::readChannelMapDbIcrr() : statement not prepared OK`

**Comment by toej93** [comment]
It's not clear if the testbed is implemented for `DETECTOR_STATION`. TB has it's own mode: `DETECTOR=3`.


<img width="936" alt="Screen Shot 2019-12-20 at 10 06 33 AM" src="https://user-images.githubusercontent.com/25533803/71280592-7e155e80-2310-11ea-8f20-48bb368504f5.png">
<img width="920" alt="Screen Shot 2019-12-20 at 10 06 03 AM" src="https://user-images.githubusercontent.com/25533803/71280593-7e155e80-2310-11ea-836a-f6c932756b9c.png">

**Comment by mingyuanlu** [comment]
Thanks for tracking that down. So if `DETECTOR_STATION=0` and `DETECTOR` is not 3, the code should stop gracefully, instead of simply segfaults. This can be done simply by checking against such incompatible combinations in the `Settings.cc` section, where other incompatible parameters are checked.

**Comment by mingyuanlu** [comment]
I implemented the check in `CheckCompatibilities` function. Mem error persists. I think this is due to `CheckCompatibilitites` being called _after_ instances of the Detector etc class objects are initialized. And the mem error happens during the instance initialization. 

I think the compatibility check should logically take place right after the setup file is read. No point in creating all the objects only to later find out you have incompatible parameters. As it's currently implemented, the `CheckCompatibilities` function takes an initialized `detector` object as an argument, but only a subset of the checks in this function utilizes it. I propose that we split this function, and keep the checks that need the `detector` object in its current place, while move the other checks to right after reading the setup file. This should solve our current issue, and is more logical from a structural point of view.

Let me know what you think.

**Comment by toej93** [comment]
That sounds good to me. Sounds more efficient than what's currently being done.

**Comment by toej93** [comment]
MYL fixed it and merged to master
